repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: check-xml

-   repo: local
    hooks:
    -   id: shell-lint
        name: "Shellscript: lint"
        entry: checksyntax/shellcheck
        language: script
        files: \.inc$
